#ifdef DEF_UN_CHECK
# undef DEF_UN_CHECK
#endif

#ifdef DEF_BIN_CHECK
# undef DEF_BIN_CHECK
#endif

#ifdef DEF_UN_IMP_CONVERT_CHECK
# undef DEF_UN_IMP_CONVERT_CHECK
#endif

#ifdef DEF_BIN_IMP_CONVERT_CHECK
# undef DEF_BIN_IMP_CONVERT_CHECK
#endif
