language: cpp

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/jessie/ llvm-toolchain-jessie-5.0 main'
    packages:
      - clang-5.0
      - clang++-5.0

script:
  - make Test CXX=clang++-5.0
