language: cpp
addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libstdc++6
      - clang-5.0
      - clang++-5.0
      - python3.5

sudo: required
script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - g++ --version
  - ls /usr/lib32/libstdc++.so.*
  - python3.5 test.py clang++-5.0
