language: cpp
addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - clang-5.0
      - clang++-5.0
      - python3.5

sudo: required
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - python3.5 test.py clang++-5.0
